from clients import create_table_clients
from collaborateurs import create_table_collaborateurs
from contrats import create_table_contrats
from evenements import create_table_evenements


create_table_clients()
create_table_collaborateurs()
create_table_contrats()
create_table_evenements()